version: '3.7'
services:
   app:
    container_name: mongodb
    image: mongo:4.2.16
    #restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: cineAPP
      MONGO_INITDB_ROOT_PASSWORD: kHzzHQ45uACiZqFO
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      #- ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks: 
      backend: 
        aliases: 
          - mongodb_host

networks:
  backend: 
    name: cine_network
    driver: bridge

volumes:
  mongodb_data_container: