FROM node:16-alpine3.11 AS development
ENV NODE_ENV development
# Add a work directory
WORKDIR /app
# Cache and Install dependencies
COPY package.json .
COPY yarn.lock .
# RUN npm i express graphql express-graphql
# RUN npm i  mongoose dotenv jsonwebtoken
# RUN npm i cookie-parser
# RUN npm i --save-dev  nodemon
# RUM sudo npm i -g pm2
RUN yarn install
# RUN node -r dotenv/config ./src/config.env
# Copy app files
# openssl genrsa -out key.pem
# openssl req -new -key key.pem -out csr.pem
# openssl x509 -req -days 9999 -in csr.pem -signkey key.pem -out cert.pem
# rm csr.pem
COPY . .
# Expose port
EXPOSE 9090
# Start the app
CMD [ "yarn", "dev" ]