version: "3.8"

services:
  app:
    container_name: cine-api
    image: cine-api
    #restart: always
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
      #- ./images:/images
    ports:
      - 9090:9090
    networks: 
      frontend: 
        aliases: 
          - api 
      backend: 
        aliases: 
          - rest   

networks:
  backend:
    external: true
    name: backend_network   
  frontend: 
    name: frontend_network
    driver: bridge